### ISSUE TITLE
keepa.com - broken on Big Sur with AdGuard nightly

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1371]
@adguard-bot commented on [Fri Oct 30 2020](https://github.com/AdguardTeam/AdguardFilters/issues/66649)

### Issue URL (Incorrect Blocking)
 [https://keepa.com](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fkeepa.com)
### Comment
> The website works fine when AdGuard is turned off globally, but disabling AdGuard in the browser for this specific website (adding to user filter) does not work.
> 
> Website also works fine in Chrome when AdGuard is enabled globally.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/cBHz1Sv.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/u4SWRPd.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Mac v2.5.1.911 nightly (CL-1.7.134)
Browser: | Safari
Stealth mode options: | Hide your search queries, <br/>Send Do-Not-Track header, <br/>Strip URLs from tracking parameters, <br/>Self-destructing first-party cookies (), <br/>Block WebRTC, <br/>Block Java
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads, <br/>EasyList, <br/>Peter Lowe's Blocklist<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances, <br/>Adblock Warning Removal List, <br/>I don't care about cookies<br/><br/><b>Security:</b><br/> Online Malicious URL Blocklist, <br/>Spam404, <br/>NoCoin Filter List<br/><br/><b>Other:</b><br/> AdGuard DNS<br/><br/><b>Language-specific:</b><br/> AdGuard Russian, <br/>AdGuard German, <br/>AdGuard Japanese, <br/>AdGuard Spanish/Portuguese, <br/>AdGuard French, <br/>EasyList China, <br/>EasyList Czech and Slovak, <br/>EasyList Italy, <br/>Official Polish filters for AdBlock, uBlock Origin & AdGuard

---

@Alex-302 commented on [Tue Nov 03 2020](https://github.com/AdguardTeam/AdguardFilters/issues/66649#issuecomment-721126804)

Cannot reproduce on macbook with the latest AdGuard.
Which macos version?

---

@dalDevelo commented on [Tue Nov 03 2020](https://github.com/AdguardTeam/AdguardFilters/issues/66649#issuecomment-721189444)

macOS 11.0.1 Beta (20B5012d)

---

@Alex-302 commented on [Tue Nov 03 2020](https://github.com/AdguardTeam/AdguardFilters/issues/66649#issuecomment-721235611)

Big Sur has a lot of problems.
Please check the latest AdGuard `nightly`
http://agrd.io/mac_nightly

---

@dalDevelo commented on [Wed Nov 04 2020](https://github.com/AdguardTeam/AdguardFilters/issues/66649#issuecomment-721448543)

I believe I am already on the latest night build: AdGuard for Mac v2.5.1.913 nightly. The ticket was opened whilst on the previous version, however, the issue remains in the latest version.

---

@Alex-302 commented on [Wed Nov 04 2020](https://github.com/AdguardTeam/AdguardFilters/issues/66649#issuecomment-721653240)

Ok, please check with disabled filters, but enabled protection.

---

@dalDevelo commented on [Wed Nov 04 2020](https://github.com/AdguardTeam/AdguardFilters/issues/66649#issuecomment-721741551)

Thanks for reopening the issue @Alex-302 

Turning off all the filters does not resolve the issue. I've gone through all the tabs in settings and I have found the culprit. Unchecking 'Automatically Filter Applications' under the network tab fixes the issue. re-enabling causes the issue to reoccur.

I also turned off all the (main) setting in the other tabs, such as stealth mode etc, but they didn't resolve the issue.

**Comment by ameshkov** [comment]
Let's try addressing it asap, the release is close

**Comment by ngorskikh** [comment]
Can't reproduce, macOS `11.0.1 Beta (20B5012d)`, Safari `14.0.1 (16610.2.11.51.4)`, AG `2.5.1.917 nightly`.
@dalDevelo, if you're still encountering this problem, we'll need debug logs to troubleshoot it: please enable debug logging (Advanced -> Logging Level), reproduce the issue, then export (Advanced -> Export Logs...) the logs. Send the file to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.
Btw, unchecking 'Automatically Filter Applications' practically means disabling AdGuard, so that is not a solution :)

**Comment by dalDevelo** [comment]
@ngorskikh Yes I still have the issue in the latest nightly build 2.5.1.917. I've just sent the requested logs over.

**Comment by ngorskikh** [comment]
@dalDevelo can you also please tell if it works in browsers other than Safari, and have you tried emptying the caches (Safari -> Preferences -> Advanced -> Show develop menu, then Develop -> Empty caches)?

**Comment by dalDevelo** [comment]
@ngorskikh I have tried emptying the caches, issue remains. Yes, this works in Chrome (latest version) with AdGuard enabled, I mentioned this in the comment section of the original report.

**Comment by dalDevelo** [comment]
Not sure if this is any use, but this is the console error message I get when trying to access Keepa.com with AdGuard enabled

![Screenshot 2020-11-10 at 13 30 24](https://user-images.githubusercontent.com/44850778/98680307-208b6580-2359-11eb-9206-10f6885044d5.png)

**Comment by dalDevelo** [comment]
Just tried again on the latest macOS beta release candidate 2 `11.0.1 (20B28)` and the issue remains.

**Comment by Chinaski1** [comment]
Hello there @dalDevelo!

Unfortunately, we cannot solve your issue without **cert.db**.

Could you send it to us?

You can find it here:

~/Library/Group/Containers/TC3Q7MAJXF.com.adguard.mac/Library/Caches/com.adguard.mac.adguard/CertCache/SSL/cert.db

We are waiting for a mail from you on devteam@adguard.com :)

**Comment by ngorskikh** [comment]
@dalDevelo it looks like a Safari or NetworkFramework + NetworkExtension bug, the only problem is we can't reproduce it on our end :( Can you see if WebSocket in Safari with AdGuard works on other sites, for example: https://www.websocket.org/echo.html ?

**Comment by dalDevelo** [comment]
@ngorskikh I am also unable to get web socket to connect on [https://www.websocket.org/echo.html](https://www.websocket.org/echo.html) in Safari with AdGuard enabled. Notably, even if I turn off the AdGuard extension in the Safari settings, it still doesn't work, I need to turn off AdGuard from the main switch in the AdGuard app, or by turning off 'automatically filter applications' in the AG network preferences.

There is nothing out of the ordinary with my network settings. IPv6 is enabled and set to automatic config.

I will send the console log over via email, let me know if you need this in a different format.

**Comment by dalDevelo** [comment]
Probably no surprise here, but issue remains on the release (non-beta) version of macOS `11.0.1 (20B29)`

**Comment by ameshkov** [comment]
@ngorskikh any ideas?

**Comment by dalDevelo** [comment]
Just to follow up on this, I think this may be an interoperability issue with AdGuard / Little Snitch. I have tried troubleshooting this further and if I disable LS from the macOS network panel via the 'make service inactive' option, the Keepa.com website also loads in this situation (even with AG enabled). However, the issue is not resolved if I disable the LS network filter via the LS settings. Either AG or LS need to be disables at the global / OS level for Keepa.com to work.

For info, I am not blocking any connections with Little Snitch, even when it is enabled, it is just used to capture and monitor outgoing network traffic from my machine.

**Comment by ameshkov** [comment]
Oh, so you're using Little Snitch. This is important indeed, thank you!

**Comment by sfionov** [comment]
Reported incompatibility with LittleSwitch to Apple:
FB8918126
https://developer.apple.com/forums/thread/667962

**Comment by jace** [comment]
I’m having this issue with Keepa’s Chrome Extension on Amazon. AdGuard version 2.5.5.993 nightly (CL-1.8.138, DNS-1.6.14). I’m on nightly for M1 support. Turning off AdGuard fixes Keepa.

**Comment by jace** [comment]
(Fixed this for now by adding keepa.com to the whitelist.)

**Comment by ngorskikh** [comment]
Highly likely fixed by `core/pull-requests/2477`

**Comment by jace** [comment]
Turns out excluding keepa.com doesn’t actually fix it. At least, these rules don’t help:

```
@@||keepa.com^$important,document
@@||dyn.keepa.com^$important,document
```

**Comment by ngorskikh** [comment]
@jace Try adding an HTTPS exclusion instead, until the fix is released.

**Comment by jace** [comment]
@ngorskikh Looks like that worked.
