### ISSUE TITLE
developer.tuya.com sites are not reachable

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1620]
@adguard-bot commented on [Wed Apr 06 2022](https://github.com/AdguardTeam/AdguardFilters/issues/114832)

### Issue URL (Incorrect Blocking)
 [https://developer.tuya.com/en/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fdeveloper.tuya.com%2Fen%2F)
### Comment
Username: @ovanbiervliet
> Tuya sites not reachable with AdGuard enabled

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/J4DRetF.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/ojDAuoq.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Mac v2.7.0.1094 release
Browser: | Safari
Stealth mode: | disabled
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Language-specific:</b><br/>AdGuard German, <br/>AdGuard Japanese, <br/>AdGuard Dutch, <br/>Adblock List for Finland, <br/>Dandelion Sprout's Nordic Filters
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js
Other extensions used: | none

---

@zloyden commented on [Fri Apr 08 2022](https://github.com/AdguardTeam/AdguardFilters/issues/114832#issuecomment-1092688814)

Not reproduced on my end. @AdguardTeam/filters-maintainers please take a look.

---

@ovanbiervliet commented on [Fri Apr 08 2022](https://github.com/AdguardTeam/AdguardFilters/issues/114832#issuecomment-1092695506)

I've checked the logs (set to debug level) and it doesn't show at all.

---

@Alex-302 commented on [Fri Apr 08 2022](https://github.com/AdguardTeam/AdguardFilters/issues/114832#issuecomment-1092707376)

Only one site can't be reached?

---

@ovanbiervliet commented on [Fri Apr 08 2022](https://github.com/AdguardTeam/AdguardFilters/issues/114832#issuecomment-1092737848)

@Alex-302 All *.tuya.com domains, doesn't happen with other websites. As soon as I disable AdGuard it works again.

---

@Alex-302 commented on [Fri Apr 08 2022](https://github.com/AdguardTeam/AdguardFilters/issues/114832#issuecomment-1092794616)

@ovanbiervliet Please test when all filters disabled. Does not look like filters related issue.

---

@ovanbiervliet commented on [Fri Apr 08 2022](https://github.com/AdguardTeam/AdguardFilters/issues/114832#issuecomment-1092865593)

Tested, no change. Also whitelisted all tuya-domains I could see in the dns-logs (nextdns):
@@||tuya.com^$important,document
@@||developer.tuya.com^$important,document
@@||*.tuya.com^$important,document
@@||*.tuyacn.com^$important,document
@@||*.tuyaus.com^$important,document
@@||*.tuyaeu.com^$important,document
There may be more domains, but the error specifically mentions the main domain.

**Comment by ameshkov** [comment]
Cannot reproduce this one as well

**Comment by ovanbiervliet** [comment]
Adguard is not configured for dns, and closing Adguard solves the problem. What else could be the cause?

**Comment by Alex-302** [comment]
@ovanbiervliet Please try to add `tuya.com` to HTTPS exclusions in AdGuard network settings.

**Comment by ameshkov** [comment]
Note that I am on AdGuard for Mac v2.8 beta so there's a chance that the issue has been already resolved.

@ovanbiervliet could you please try the beta version?

https://adguard.com/beta.html

Beta versions are rather stable and safe to use.

**Comment by ViRb3** [comment]
I am using 2.7.0.1094 release (CL-1.8.276, DNS-1.6.72) and no issues here.

**Comment by ovanbiervliet** [comment]
I already had *.tuya.com in the https-exclusion list. Application version 2.8.0.1132 beta (CL-1.9.60, DNS-1.7.22) did not resolve this.

**Comment by ovanbiervliet** [comment]
Fwiw, as soon as I uncheck "Automatically filter applications", I can reach the site.

**Comment by ameshkov** [comment]
It seems that to troubleshoot this issue, we need to analyze the app logs.

Here's what we need you to do:

1. Menu -> Advanced -> Logging level -> Debug
2. Reproduce the issue (and remember the exact time when it happened).
3. Menu -> Advanced -> Export Logs and System Info...
4. Send the archive to `apple@adguard.com` and mention this issue number in the subject

**Comment by ovanbiervliet** [comment]
You've got mail - thanks.

**Comment by sfionov** [comment]
@ovanbiervliet We see NextDNS app in your log, can your please try with it disabled?

I think this can be an issue in our VPN-compatibility workaround.

Btw you may setup your NextDNS profile in the DNS section of Adguard's settings.

**Comment by ovanbiervliet** [comment]
Disabling NextDNS did not help. 

I now added NextDNS url as a custom DNS entry in AdGuard.

**Comment by sfionov** [comment]
Can you please check that NextDNS network service is not active in "System settings -> Network"? Do you have any other third-party network services there?

**Comment by ovanbiervliet** [comment]
I had already checked it 😉 and there are no other services active.
