### ISSUE TITLE
Add support for HTTP/3 (IETF QUIC) ("h3" protocol)

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#487]
But before lets see who will support it.

**Comment by sfionov** [comment]
@TPS No, IETF QUIC and existing QUIC are different protocols.
IETF QUIC is split to QUIC transport (with modified TLS1.3 handshake) and HTTP over QUIC (hq) based on modified HTTP/2.
Google QUIC is more solid and have different Alt-Svc/ALPN protocol name.

**Comment by sfionov** [comment]
nghq seems to be abandoned. Current implementations:

HTTP/3 QUIC transport:
https://github.com/ngtcp2/ngtcp2

HTTP/3 application protocol:
https://github.com/cloudflare/quiche (Rust, C bindings exist)
https://github.com/ngtcp2/nghttp3

**Comment by DBotThePony** [comment]
nginx is getting official support for QUIC: https://quic.nginx.org/

**Comment by ameshkov** [comment]
Just a short update on this.

We did make an internal prototype of CoreLibs with HTTP/3 support, but we're not yet happy with how it works. More work is required.

**Comment by Rtizer-9** [comment]
Meanwhile can you please add an option to allow quic protocol though instead of blocking everything quic on android.

Option on per app basis will be great. I need it for some testing purpose. I'll be grateful if you can do that before the proper quic/https3 filtering comes in adguard.

**Comment by sfionov** [comment]
@Rtizer-9 Since Adguard 3.6.5 release, QUIC is not blocked in apps without HTTPS filtering on. (This applies to Local VPN mode only).

If you still have issues, there is also an option in advanced settings with list of app uids for explicit QUIC bypass - `pref.quic.bypass.packages`

**Comment by Rtizer-9** [comment]
Oh great. It escaped my attention. Thanks.

**Comment by ammnt** [comment]
Any update of this? HTTP3 support for NGINX is coming soon!🎉

**Comment by stevenzhu25** [comment]
IETF recently published HTTP/3 as RFC 9114. Can we get any status update or (more distantly) a timeline for HTTP/3 support within AdGuard products?

Thanks!

**Comment by ryboe** [comment]
I would like to see this prioritized as well. HTTP/3 is a big performance win for mobile. It's a shame to be missing out on the benefits of a UDP-based protocol. If HTTP/3 support gets added as experimental, I'll enable it so hopefully the devs can collect some telemetry.

**Comment by TPS** [comment]
I'm waiting for this before I enable it  on my devices across the board.  Can't go back to the pre-AG days anymore!

**Comment by ryboe** [comment]
[HTTP/3 is currently 25.5% of website traffic](https://w3techs.com/technologies/details/ce-http3), according to w3tech.com.

**Comment by TPS** [comment]
> But before lets see who will support it.

Looks like mainly properties from Google, Facebook, Microsoft, &c, per above.  

@ryboe Thanks for the link.  That continuous monitoring info seems very helpful.

**Comment by zubrRB** [comment]
dnscrypt-proxy version 2.1.2: Support for DoH over HTTP/3 (DoH3, HTTP over QUIC) has been added.

**Comment by stevenzhu25** [comment]
It's almost a year since the last comment and the target corelibs label has not been updated for half a year now... Would this be possible released in v1.12?

**Comment by ameshkov** [comment]
@stevenzhu25 it will be avaialble in AdGuard versions that use CoreLibs v1.12, but behind a low-level flag.

Expect it to arrive to the nightly channel in about a month from now.

**Comment by sfionov** [comment]
Experimental HTTP/3 support has been implemented in CoreLibs 1.12.

It will be available in the next release cycle of desktop AG products, although it is disabled by default.

It should work ok is Safari and Edge.
But at this time it will not work in Chrome unless `--origin-to-force-quic-on=` is specified with name of site.

It is because Chrome's QUIC certificate verification code does not expect middlebox CA certs, which prevents HTTP/3 from being filtered by default. However, they have a task to unify TLS and QUIC verification (https://crbug.com/848277), so it may change in future.

**Comment by szhu25** [comment]
> It should work ok in Safari and Edge.

Thanks for the update! Any testing to see if it would work in Firefox?

**Comment by sfionov** [comment]
@szhu25 Yes, it will work Firefox.

**Comment by TPS** [comment]
@ameshkov What are the target nightly version #s for each platform, _especially_ mobile?

**Comment by ameshkov** [comment]
Not yet planned on exact nightlies of Android, but it will be done in v4.2 indeed.

**Comment by war59312** [comment]
See was enabled in v7.15.0-beta-1 for firefox and edge.

No luck here it seems. Enabled the advanced setting for http3 filtering and using Edge on Win11 22H2.

https://quic.nginx.org/quic.html still shows using HTTP and https://cloudflare-quic.com/ still shows using HTTP/2 after many refreshes.

**Comment by ameshkov** [comment]
Note, that it will not work in Chromium-based browsers until [this bug](https://crbug.com/848277) is resolved.

**Comment by BooBerry** [comment]
It does work, kinda, in Firefox. Even though HTTP/3 is used for some things on sites like Google, for others like Facebook and https://cloudflare-quic.com/ it's still using HTTP/2 even though 1) it's enabled in AG's advanced settings and 2) it's enabled in Firefox.

**Comment by sfionov** [comment]
@BooBerry Can you please send a crash report and say what time report is sent?

About falling back to HTTP/2 - I reproduced it on Facebook and https://cloudflare-quic.com/, thanks.

**Comment by BooBerry** [comment]
@sfionov Sent a report in, #800123 is the number, Crash happened at 1:09 PM my time, sent in within 2 minutes ago at 1:11 PM my time.

Hopefully that helps. :)

**Comment by BooBerry** [comment]
Also did some more HTTP/3 testing in Firefox (developer console with the Protocol tab enabled) and it looks like with AG enabled it only uses HTTP/3 for one connection, for the RotateCookies connection. I'm seeing this on https://www.google.com and https://news.google.com at the moment.

Other sites like https://www.twitter.com it isn't used at all, whereas without AG (testing with a portable Firefox not filtered by AG but set up exactly the same) I see HTTP/3 being used quite a bit.

Same with https://http3.is where Firefox with AG falls back to HTTP/2 only, and Firefox alone uses HTTP/3.

**Comment by sfionov** [comment]
@BooBerry A fix is available in Mac version 2.12 beta 1 and Windows version 7.15 nightly 10+ (and will be included into beta 2 soon).

**Comment by BooBerry** [comment]
For which issue? The crash issue or the HTTP/3 not working on sites in Firefox issue?

**Comment by sfionov** [comment]
@BooBerry HTTP/3 filtering in Firefox should be fixed.

As of "HTTP/3 for DNS-over-HTTPS", it is known issue that it crashes, it is recommended not to switch on this feature in 7.15 release.

**Comment by BooBerry** [comment]
Just double checked 7.15 nightly 12 and here's the results.

1) Random AG service crashes still exists when **Filter HTTP/3** and **Use HTTP/3 for DNS-over-HTTPS** are both enabled at the same time. If I disable Use HTTP/3 for DNS-over-HTTPS, no more crashes of the AG service.

2) Just tested Firefox 117.0.1 with it (and a cleared browser cache) and it's still not using HTTP/3 for anything but RotateCookies. I'm going to do a backup of the Firefox profile and first try deleting all cookies then try a clean profile.

**Comment by sfionov** [comment]
Did you try reloading page twice? Few reloads may be needed to switch to HTTP/3 - after first reload Alt-Svc is cached, and after second it is applied.

**Comment by BooBerry** [comment]
Yeah, just double checked with a clean profile in Firefox, HTTP/3 isn't being used with AG enabled (and Filter HTTP/3 enabled).

And yes, I reloaded multiple times. It works with AG disabled, of course.

**Comment by sfionov** [comment]
There was an issue in driver configuration that blocked HTTP/3 from being filtered under Windows. The fix will be included into the next beta.

**Comment by BooBerry** [comment]
Groovy, I assume it'll be in the next nightly (nightly 17 or newer) too?

**Comment by TPS** [comment]
> Note, that it will not work in Chromium-based browsers until [this bug](https://crbug.com/848277) is resolved.

@ameshkov, @sfionov: Just to confirm, the announcement re: this issue @ https://github.com/AdguardTeam/AdguardForAndroid/releases/tag/v4.2-beta-1 really only means Ff-based browsers, correct?  Chromium-based are still SOL d/t this bug?  Or was there progress somehow, & this issue wasn't updated?  I'm still having very similar behavior as @BooBerry detailed previously, so wanted to verify expectations.

**Comment by BooBerry** [comment]
No, it won't work in Chromium-based browsers right now until Google resolves it, just Firefox (and I think Safari?) right now.

The currently nightly build *does* work in Firefox finally, but it's not any faster than HTTP/2 in my own testing, but it's something. :D

**Comment by TPS** [comment]
> @TPS MS Edge should work too, it is Chromium-based but have, I believe, another QUIC implementation.

@sfionov MSEdge _Android_ is specifically failing.  It says it'll accept QUIC on 1st connection (0RTT, IIUC), but all QUIC connections fail in actual use, using test sites as provided above.

Would someone confirm/deny my experience?

**Comment by BooBerry** [comment]
No-go for Edge here on Windows, unfortunately.

**Comment by TPS** [comment]
@BooBerry Just to confirm:  did you force on the QUIC options under [edge://flags](edge://flags)?  I did so under Android to give it the best chance of success.

**Comment by BooBerry** [comment]
Of course, I've had the QUIC option force enabled in Edge (and Chrome) the whole time.

**Comment by sfionov** [comment]
@TPS @BooBerry Tested on my Mac, it doesn't work too. Seems that previous test was incomplete. So it is true, feature is available only on FF and Safari. :(

You may also use `--origin-to-force-quic-on=www.google.com:443` Chrome command line option to force quic on your favorite domain in Chrome, but it is not a solution for all sites.

**Comment by TPS** [comment]
> You may also use `--origin-to-force-quic-on=www.google.com:443` Chrome command line option to force quic on your favorite domain in Chrome, but it is not a solution for all sites.

@sfionov This causes QUIC to work while on AG?  Is this somehow different than the `://flags` options as mentioned previously?

**Comment by sfionov** [comment]
@TPS This option disables certificate verification for that site and forces HTTP/3. So yes, it should work with AG. But if you try to enable it on all sites, every non-HTTP/2 site will be broken.

**Comment by szhu25** [comment]
I tested http3 using AdGuard for Android beta with Firefox, and it doesn't seem like http3 is working.

**Comment by sfionov** [comment]
@jslawler CoreLibs are only used on Android, Mac and Windows. 

http3.is is hard to get working even without AdGuard - several reloads are needed, and result is not guaranteed

**Comment by sfionov** [comment]
@szhu25 There is fix in Adguard for Android 4.2 beta 2 for issue that prevented HTTP/3 in Firefox from being filtered

**Comment by szhu25** [comment]
> @szhu25 There is fix in Adguard for Android 4.2 beta 2 for issue that prevented HTTP/3 in Firefox from being filtered

I can confirm that! HTTP/3 in Firefox is working for both AdGuard for Windows stable & AdGuard for Android beta 2.

**Comment by sfionov** [comment]
@Rtizer-9 If you use "Automatic proxy mode" then HTTP/3 filtering will not be available. Unfortunately, it only works in default mode right now. UDP filtering in automatic proxy mode requires more work which is not done yet.

**Comment by Rtizer-9** [comment]
Oh ok. Thanks for clarifying because there isn't any official information regarding this in the kb or anywhere else, even in the recently released latest beta changelog or the http3 config in low level setting itself....no issues...will wait.
