### ISSUE TITLE
svyaznoy.ru is not working

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#674]
@adguard-bot commented on [Fri Jan 11 2019](https://github.com/AdguardTeam/AdguardFilters/issues/28177)

### Issue URL (Incorrect Blocking)
[http://svyaznoy.ru](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fsvyaznoy.ru)
### Comment
Username: @AlexMarken
> При включенной функции AdGuard "Защита включена и работает" (антибаннер - вкл, антитрекинг - выкл, антифишинг - вкл) перестаёт работать сайт Интернет магазина Связной Ru.
> 
> При переходе на svyaznoy.ru происходит редирект, как на первом скрине. После чего, идёт постоянная загрузка страницы.
> 
> Отключение всех фильтров не помогло. Проблема решается выключением опции "Защита включена и работает". Если хоть один из компонентов работает (антибаннер, антитрекинг, антифишинг), сайт не грузится. Проблеме уже больше 2х месяцев.
> 
> OS: macOS 10.14.2.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/duOQSgq.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/DDE1l1t.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Mac
AdGuard version: | 1.5.14
Browser: | Safari
Filters: | AdGuard Russian,<br>EasyList,<br>AdGuard Safari,<br>AdGuard Annoyances,<br>AdGuard Base,<br>AdGuard Social Media,<br>AdGuard Experimental

**Comment by ameshkov** [comment]
Seems to be working okay with the nightly version of AdGuard. We need to re-check it later when CoreLibs 1.3 will be used by AG for Mac.

**Comment by AlexMarken** [comment]
@ameshkov, hello! When will bug fix published for macOS?

**Comment by ameshkov** [comment]
@AlexMarken well, the first AG for Windows nightly will likely to be released next week, but it will take it at least a month or two to make it to the stable channel.

**Comment by AlexMarken** [comment]
@ameshkov nice! When released for macOS?

**Comment by ameshkov** [comment]
@AlexMarken hopefully, in a month or so. The first beta will be published next week.

**Comment by AlexMarken** [comment]
@ameshkov ok)

**Comment by sfionov** [comment]
Svyaznoy.ru uses Variti DoS protection.
AdGuard is somehow triggering this protection (Non-whitelisted ClientHello?)
DoS protection page is executed too slow in Safari (about 28 seconds) because some cryptography is used to prevent automatic extraction of token.
DoS protection page shows again. May be token has been expired or the same conditions met that lead DOS protection to trigger.

**Comment by ameshkov** [comment]
Well, so basically we should make sure the DoS protection is not triggered
by making ClientHello the same (same ciphers, extensions, maybe the same
order?)

**Comment by sfionov** [comment]
Users are also reporting problems with Firefox. As a workaround for incompatibility of their protection check with non-V8 browsers, I suggest adding check.svyaznoy.ru to the list of HTTPS exclusions on all platforms.

**Comment by sfionov** [comment]
Domain ohio8.vchecks.me should also be added

**Comment by ameshkov** [comment]
Done:
https://github.com/AdguardTeam/HttpsExclusions/commit/a2f98cbe0f14e8cc3bd1ec2b199fbcc644783d01

**Comment by akmLaVx** [comment]
Issue is back. macOS 10.14, unknown (presumably latest) Safari.

<details>
<summary>Screenshot</summary>
<img width="1440" alt="Снимок экрана 2019-07-17 в 13 04 17 1" src="https://user-images.githubusercontent.com/33634917/61519941-c654eb80-aa15-11e9-9c30-4087955cb1db.png">
</details>

More details in ticket 1023240

**Comment by ameshkov** [comment]
@akmLaVx check that svyaznoy.ru is in HTTPS exclusions

**Comment by ameshkov** [comment]
Temp fix: https://github.com/AdguardTeam/HttpsExclusions/commit/0e9a999b587635174f4ce686fc9f05340dc378dc

**Comment by sfionov** [comment]
Merged into https://github.com/AdguardTeam/CoreLibs/issues/1223
